//*> API CALLING CONSTANTS
export const GET_API = 'GET';
export const POST_API = 'POST';
export const PUT_API = 'PUT';
export const DELETE_API = 'DELETE';
export const UPDATE_API = 'PUT';
export const PATCH_API = 'PATCH';

//*> USER CONSTATNS
export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED"
export const LOGIN_USER_SUCCESS = "LOGIN_USERS_SUCCESS"
export const LOGIN_USERS_FAILED = "LOGIN_USERS_FAILED"

export const GET_CATEGORIES_REQUESTED = "GET_CATEGORIES_REQUESTED"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED"

//*>APP LOADER
export const START_SPINNER = "START_SPINNER"
export const STOP_SPINNER = "STOP_SPINNER"


//*> ERROR MODAL
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL"  
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL"
